os:
  - osx
  - linux
language: dart
sudo: false
dart:
  - stable
dart_task:
  - test: --platform vm
before_script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi'