name: clippy
description: A library to access the clipboard (copy/paste) for server and browser.
version: 0.0.1
homepage: https://github.com/andresaraujo/clippy
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
  browser: any
